[project]
name = "wifi2usb"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "grbl-streamer>=2.0.2",
    "loguru>=0.7.3",
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
    "websockets>=15.0.1",
]
